from typing import Dict, Iterator, Optional, Tuple

class SummedRadixTree:
    def __init__(self, items: Optional[Dict[int, int]] = None) -> None: ...
    def contains(self, element: int) -> bool: ...
    def __contains__(self, element: int) -> bool: ...
    def add(self, element: int, value: int) -> "SummedRadixTree": ...
    def union(self, other: "SummedRadixTree") -> "SummedRadixTree": ...
    def total(self) -> int: ...
    def __or__(self, other: "SummedRadixTree") -> "SummedRadixTree": ...
    def __add__(self, other: Tuple[int, int]) -> "SummedRadixTree": ...
    def __getitem__(self, element: int) -> int: ...
    def __hash__(self) -> int: ...
    def __iter__(self) -> Iterator[Tuple[int, int]]: ...
    def __len__(self) -> int: ...

class LowPrecisionSizeSketch:
    def __init__(self) -> None: ...
    def add(self, element: int, value: float) -> None: ...
    def total(self) -> float: ...
    def union(self, other: "LowPrecisionSizeSketch") -> "LowPrecisionSizeSketch": ...

class MediumPrecisionSizeSketch:
    def __init__(self) -> None: ...
    def add(self, element: int, value: float) -> None: ...
    def total(self) -> float: ...
    def union(
        self, other: "MediumPrecisionSizeSketch"
    ) -> "MediumPrecisionSizeSketch": ...

class HighPrecisionSizeSketch:
    def __init__(self) -> None: ...
    def add(self, element: int, value: float) -> None: ...
    def total(self) -> float: ...
    def union(self, other: "HighPrecisionSizeSketch") -> "HighPrecisionSizeSketch": ...

class SetMembershipSketch:
    def __init__(self) -> None: ...
    def add(self, item) -> "SetMembershipSketch": ...
    def add_all(self, items) -> "SetMembershipSketch": ...
    def union(self, other: "SetMembershipSketch") -> "SetMembershipSketch": ...
    def is_subset_of(self, other: "SetMembershipSketch") -> bool: ...
    def __or__(self, other: "SetMembershipSketch") -> "SetMembershipSketch": ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(bytes: bytes) -> "SetMembershipSketch": ...