from typing import Any, Final, final

@final
class EstimatorPrecision:
    NoEstimates: Final[EstimatorPrecision]
    Low: Final[EstimatorPrecision]
    Medium: Final[EstimatorPrecision]
    High: Final[EstimatorPrecision]
    Exact: Final[EstimatorPrecision]
    def __int__(self, /) -> int: ...

@final
class HeapDumpExplorer:
    def __new__(cls, /, db_path: str) -> HeapDumpExplorer: ...
    def find_path_between_objects(
        self, /, start_id: int, end_id: int, avoiding_ids: set[int]
    ) -> list[ObjectSummary] | None: ...
    def find_largest_common_reachable_object(
        self, /, obj1_id: int, obj2_id: int
    ) -> int | None: ...
    def get_count_for_type(self, /, typename: str) -> int: ...
    def get_object(self, /, obj_id: int) -> ObjectRecord | None: ...
    def get_objects_by_type(
        self, /, typename: str, page: int | None
    ) -> list[ObjectSummary]: ...
    def get_objects_by_type_ordered_by_size(
        self, /, type_name: str, subtree_size: bool, page: int | None
    ) -> list[ObjectSummary]: ...
    def get_page_count_for_type(self, /, typename: str) -> int: ...
    def get_type_summaries(self, /) -> list[tuple[Any, TypeSummary]]: ...
    def import_lines(
        self, /, lines: Any, estimator_precision: EstimatorPrecision
    ) -> None: ...

@final
class ObjectRecord:
    @property
    def id(self, /) -> int: ...
    @property
    def references(self, /) -> list[ObjectSummary]: ...
    @property
    def referrers(self, /) -> list[ObjectSummary]: ...
    @property
    def size(self, /) -> int: ...
    @property
    def subtree_size(self, /) -> int | None: ...
    @property
    def type(self, /) -> str: ...
    @property
    def value(self, /) -> str | int | float | None: ...

@final
class ObjectSummary:
    @property
    def id(self, /) -> int: ...
    @property
    def size(self, /) -> int: ...
    @property
    def subtree_size(self, /) -> int | None: ...
    @property
    def type(self, /) -> str: ...
    @property
    def value(self, /) -> str | int | float | None: ...

@final
class SummedRadixTree:
    def __add__(self, /, other: tuple) -> SummedRadixTree: ...
    def __contains__(self, /, element: int) -> bool: ...
    def __getitem__(self, /, element: int) -> int: ...
    def __hash__(self, /) -> int: ...
    def __iter__(self, /) -> _Iterator: ...
    def __len__(self, /) -> int: ...
    def __new__(cls, /, items: dict | None = None) -> SummedRadixTree: ...
    def __or__(self, /, other: SummedRadixTree) -> SummedRadixTree: ...
    def __sizeof__(self, /) -> int: ...
    def add(self, /, element: int, value: int) -> SummedRadixTree: ...
    def contains(self, /, element: int) -> bool: ...
    def total(self, /) -> int: ...
    def union(self, /, other: SummedRadixTree) -> SummedRadixTree: ...

@final
class TypeSummary:
    @property
    def count(self, /) -> int: ...
    @property
    def total_size(self, /) -> int: ...

@final
class _Iterator:
    def __iter__(self, /) -> _Iterator: ...
    def __next__(self, /) -> tuple[int, int]: ...
